spring:
  profiles: prod

  datasource:
    url: jdbc:postgresql://viaduct.proxy.rlwy.net:44090/railway
    driverClassName: org.postgresql.Driver
    username: postgres
    password: kBhDlKRqmfgBlSVYyAzoiWJnwcXCrivz

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 44090
