spring:
  profiles: prod

  datasource:
    url: jdbc:postgresql://viaduct.proxy.rlwy.net:37462/railway
    driverClassName: org.postgresql.Driver
    username: postgres
    password: xvkpsgZgDAeUSrjdlQsLKanFEUUnZCKW

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect



  server:
    port: 37462
